### ISSUE TITLE
Errors/warnings

### ISSUE THREAD

**Issue by sasp1** [a-holdet/DTUPay#17]
Jan 13, 2021 9:15:53 PM org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine finalize
WARN: RESTEASY004687: Closing a class org.jboss.resteasy.client.jaxrs.engines.ApacheHttpClient43Engine instance for you. Please close clients yourself.

RabbitMQTest hænger, hvis ikke RabbitMQ er startet væsentligt i forvejen

**Comment by IIIV** [comment]
Problemet var at vi kun lukkede for de forbindelser vi lavede til serveren og ikke clienten som køre.
