### ISSUE TITLE
[SETUP Git] Give Hubert developer rights on GitHub

### ISSUE THREAD

**Issue by BenjaminLam** [a-holdet/DTUPay#36]

**Comment by IIIV** [comment]
Behøves dette når repo'et er åbent? Jeg kan fint hente koden ned og se vores projekt board uden af være logget ind.

**Comment by BenjaminLam** [comment]
Så gør det nok ikke. Det står bare specifikt i projekt beskrivelsen at han skal have adgang til at tilgå det og hente koden :) Men hvis man sagtens kan uden at være logget ind, så er det jo fint :)
