### ISSUE TITLE
Installation of RabbitMQ on VM

### ISSUE THREAD

**Issue by BenjaminLam** [a-holdet/DTUPay#5]

**Comment by IIIV** [comment]
Jeg har taget et kig på demo projektet og eftersom vi køre kommer til at køre alle vores microservices på samme interne netværk så giver det bedst mening at køre RabbitMQ i en container ved siden af vores microservices. 
Vi kan eventuelt bruge et wait-for-it.sh script (https://docs.docker.com/compose/startup-order/) til at være sikker på RabbitMQ køre før vores andre containers "starter". Jeg har prøvet det med demo projektet hvor jeg har fået det til at virke.

**Comment by christianhjelmslund** [comment]
@IIIV er det ikke "bare" at i vores docker-compose have "depends_on: rabbitMQ" i alle de containere der er afhængige af rabbtMQ containeren er oppe at køre? Eller wait-for-it.sh skal sikre sig at rabbitMQ helt 100% er oppe at køre, hvor depends_on ikke nødvendigvis gør det (sagde Hubert vist i en video).

**Comment by IIIV** [comment]
depends_on ser kun på om containeren er startet, ikke om den service i containeren er startet. Service 1 i demo'en fejler ved startup hvis man ikke venter på rabbitMQ er helt startet.

**Comment by christianhjelmslund** [comment]
Ah, makes sense

**Comment by IIIV** [comment]
Vi køre med rabbitMQ i docker så lukker denne issue.
